### ISSUE TITLE
Doesn't work with HtmlWebpackPlugin v.4

### ISSUE THREAD

**Issue by insanecoding** [Cap32/html-webpack-banner-plugin#2]
Stopped working after `HtmlWebpackPlugin` major update to version 4.

When I try to run, it gives me this:

```
/Users/dmitry/Projects/b2b-portal/frontend/node_modules/html-webpack-banner-plugin/index.js:30
                        callProcess = processing.tap.bind(processing, pluginHook);
                                                 ^

TypeError: Cannot read property 'tap' of undefined
    at /Users/dmitry/Projects/b2b-portal/frontend/node_modules/html-webpack-banner-plugin/index.js:30:29
    at SyncHook.eval (eval at create (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at run (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/fork-ts-checker-webpack-plugin/lib/index.ts:326:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:5:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/lib/Compiler.js:312:24)
    at processOptions (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack-cli/bin/cli.js:353:14)
    at /Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/dmitry/Projects/b2b-portal/frontend/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The case is that `HtmlWebpackPlugin` hooks were changed:
https://github.com/jantimon/html-webpack-plugin#events

**Comment by shahzeb1** [comment]
Because of this issue, this plugin is effectively useless. And looks like maintainer isn't maintaining it anymore :(
